dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "7"
cache:
  yarn: true
script:
  - set -e
  - yarn lint
  - WT_DEBUG=true yarn test test/LifToken.js test/Crowdsale.js test/MarketValidationMechanism.js test/VestedPayment.js
  - WT_DEBUG=true GEN_TESTS_QTY=40 yarn test test/CrowdsaleGenTest.js
after_script:
  - yarn run coveralls
